import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const finkHeavy = localFont({
  src: "../public/FinkHeavy.ttf",
  variable: "--font-fink-heavy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={finkHeavy.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
